### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by Hazel-Eye**
edit so links can be placed on the landing page of the wiki for quick access.
hopefully the format for links work with images or ill look a bit silly.

sprites will have to be added later.

i think it should work but im unsure how it will show up in window.

whoever wrote this: "but most of the time you are just trapped in a room and never able to break free or just thrown into space for no reason at all." 

NO JUST NO. DO NOT WRITE THAT LANGUAGE. IT MAKES PEOPLE LESS LIKELY TO PLAY THE GAME LIKE WDF!!!!
its like saying "if you play this, you'll be locked in a box and be able to do nothing.. not even play the game or roleplay or do anything at all. So theres no reason to start."

Whats the point of playing the game if its like that?

Feel free to edit this as needed.

### CODE REVIEW

**Comment by corp-0** [comment]
No idea why @waffielz haven’t said anything about this pr. It looks good, I need to confirm that’s the syntax for images, but that’s fine.

Try adding the images in this pr so we see them right after merging.

**Comment by Hazel-Eye** [comment]
Images should have been added, added a simple banner as a tester. a custom designed one could be good. if can get a budget on it and a specific size looking for someone on deviantart to do a basic one could be nice. alternatively on the wiki, if you can use the sides of the page rather than everything being relagated to the central margain. a star background like https://unitystation.org/ might look nice. paralax maby? either way, hope this format works.

**Comment by Hazel-Eye** [comment]
won't be able to see how good it looks without doing a test view. if you do, please send me a screenshot with some comments if you want me to edit it and I'll probably eventually get to it... otherwise feel free to edit it yourself

**Comment by braincrab** [comment]
Probably said nothing since he doesn't read this. looking at this RN and it seems fine.

**Comment by braincrab** [comment]
lets see if this works, we can remove it later if it doesnt.

**Pull request merged**
