### PR TITLE
Add a little flavour

### PR DESCRIPTION
**Pull request by KingRed31**

### CODE REVIEW

**Comment by PerfectTangent** [comment]
Cute, but it's best to not attach any specific fictitious or player character inserts to quotes made on the wiki. Ditto for #25.

**Comment by ElLimitador** [comment]
im actually pretty on favor of making quotes on gameplay, because it helps getting the new player get into the mindset of a player

**Comment by KingRed31** [comment]
> im actually pretty on favor of making quotes on gameplay, because it helps getting the new player get into the mindset of an average player

I feel like if we get the correct tone, it can ready the player into the robust-style, this station is a dangerous place that will probably kill you, mindset.

**Comment by corp-0** [comment]
tg's wiki also has quotes like these. I think it is good.

**Pull request merged**
